# see https://yun.yunyoujun.cn/guide/config.html

# light | dark | auto | time
mode: light
comment:
  enable: true
reward: #打赏
  enable: false
notice:
  enable: false
  content: hello, world!
banner:
  enable: true
  title: 星海如歌，虚舟泛白
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
wordcloud:
  enable: true
codeblock:
  copy_btn: true
  theme:
    light: atom-one-light # github atom-one-light xcode lightfair
    dark: tomorrow-night-blue #tomorrow-night-blue atom-one-dark
creative_commons:
  license: by
  post: true
  language: deed.zh
# 点击页面的烟花效果
fireworks:
  enable: false
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'
# 随机多边形背景
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5